### PR TITLE
Fix bad union type of `fill`

### LINKED ISSUE #32: fill argument has ill-defined type / code doesn't work if fill is Vector
https://github.com/TulipaEnergy/TulipaIO.jl/blob/e5c2be1925dc2522f0f83b05521d375c98ed9c9b/src/fmtsql.jl#L50

The `Vector::Any` becomes `Vector`, so that is ignored. But most important, the mixed type logic doesn't work. If `fill` is a Vector, then the code will fail because `if fill` doesn't work - i.e., `Vector` is not a `Bool`.

I think a better alternative would be to have another keyword argument to pass the `Vector` information.

### PR DESCRIPTION
**Pull request by suvayu**
Fixes #32

### CODE REVIEW

File: test/test-pipeline.jl [hunk 1]
```diff
@@ -75,33 +75,48 @@ end
...
+        @testset "no filling for missing rows" begin
+            df_res = TIO.create_tbl(con, csv_path, csv_fill; opts..., fill = false)
+            df_ref = DF.DataFrame(CSV.File(csv_fill; header = 2))
+            # NOTE: row order is different, join to determine equality
+            cmp = join_cmp(df_res, df_ref, ["name", "investable"]; on = :name)
+            @test ifelse.(
+                ismissing.(cmp.investable_1),
+                cmp.source .== "left_only",
+                cmp.source .== "both",
+            ) |> all
```
Comment (abelsiqueira) [inline test/test-pipeline.jl:93]:
```suggestion
            @test subset(cmp, :investable_1 => ismissing).source .== "left_only" |> all
            @test subset(cmp, :investable_1 => !ismissing).source .== "both" |> all
```

File: test/test-pipeline.jl [hunk 2]
```diff
@@ -75,33 +75,48 @@ end
...
+        end
+
         @testset "back-filling missing rows" begin
+            df_res = TIO.create_tbl(con, csv_path, csv_fill; opts..., fill = true)
+            df_exp = DF.DataFrame(CSV.File(csv_copy; header = 2))
+            cmp = join_cmp(df_exp, df_res, ["name", "investable"]; on = :name)
+            @test all(cmp.investable .== cmp.investable_1)
+            @test cmp.source |> x -> all(i -> i == "both", x)
```
Comment (abelsiqueira) [inline test/test-pipeline.jl:101]:
```suggestion
            @test cmp.source .== "both" |> all
```

File: test/test-pipeline.jl [hunk 3]
```diff
@@ -75,33 +75,48 @@ end
...
             df_res = TIO.create_tbl(
                 con,
                 csv_path,
                 csv_fill;
-                on = [:name],
-                cols = [:investable],
+                opts...,
                 fill = true,
-                show = true,
+                values = Dict(:investable => true),
```
Comment (abelsiqueira) [inline test/test-pipeline.jl:111]:
```suggestion
                fill_values = Dict(:investable => true),
```

File: test/test-pipeline.jl [hunk 4]
```diff
@@ -75,33 +75,48 @@ end
...
-            # NOTE: row order is different, join to determine equality
-            cmp = join_cmp(df_exp, df_res, ["name", "investable"]; on = :name)
-            @test cmp.source |> x -> all(i -> i == "both", x)
+            df_ref = DF.DataFrame(CSV.File(csv_fill; header = 2))
+            cmp = join_cmp(df_res, df_ref, ["name", "investable"]; on = :name)
+            @test ifelse.(
+                ismissing.(cmp.investable_1),
+                cmp.investable .== true,
+                cmp.investable .== cmp.investable_1,
+            ) |> all
```
Comment (abelsiqueira) [inline test/test-pipeline.jl:119]:
```suggestion
            @test subset(cmp, :investable_1 => ismissing).investable |> all
```

File: test/test-pipeline.jl [hunk 5]
```diff
@@ -164,16 +178,36 @@ end
...
+
+        @testset "back-filling missing rows w/ alternate values" begin
+            tbl_name = TIO.create_tbl(
+                con,
+                "no_assets",
+                csv_fill;
+                variant = "alt_assets_filled_alt",
+                opts...,
+                fill = true,
+                values = Dict(:investable => true),
```
Comment (abelsiqueira) [inline test/test-pipeline.jl:200]:
```suggestion
                fill_values = Dict(:investable => true),
```

File: test/test-pipeline.jl [hunk 6]
```diff
@@ -164,16 +178,36 @@ end
...
-                cols = [:investable],
+                opts...,
                 fill = true,
             )
             df_res = DF.DataFrame(DBInterface.execute(con, "SELECT * FROM $tbl_name"))
             df_exp = DF.DataFrame(CSV.File(csv_copy; header = 2))
             # NOTE: row order is different, join to determine equality
             cmp = join_cmp(df_exp, df_res, ["name", "investable"]; on = :name)
+            @test all(cmp.investable .== cmp.investable_1)
             @test cmp.source |> x -> all(i -> i == "both", x)
```
Comment (abelsiqueira) [inline test/test-pipeline.jl:189]:
```suggestion
            @test cmp.source .== "both" |> all
```

File: test/test-pipeline.jl [hunk 7]
```diff
@@ -164,16 +178,36 @@ end
...
+                values = Dict(:investable => true),
+            )
+            df_res = DF.DataFrame(DBInterface.execute(con, "SELECT * FROM $tbl_name"))
+            df_ref = DF.DataFrame(CSV.File(csv_fill; header = 2))
+            cmp = join_cmp(df_res, df_ref, ["name", "investable"]; on = :name)
+            @test ifelse.(
+                ismissing.(cmp.investable_1),
+                cmp.investable .== true,
+                cmp.investable .== cmp.investable_1,
+            ) |> all
```
Comment (abelsiqueira) [inline test/test-pipeline.jl:209]:
```suggestion
            @test subset(cmp, :investable_1 => ismissing).investable |> all
```

File: src/pipeline.jl [hunk 8]
```diff
@@ -158,12 +159,13 @@ function create_tbl(
...
     variant::String = "",
-    fill::Union{Bool,Vector::Any} = true,
+    fill::Bool = true,
+    values::Union{Missing,Dict} = missing,
     tmp::Bool = false,
     show::Bool = false,
 )
     sources = [fmt_source(con, src) for src in (base_source, alt_source)]
-    query = fmt_join(sources...; on = on, cols = cols, fill = fill)
+    query = fmt_join(sources...; on = on, cols = cols, fill = fill, values = values)
```
Comment (abelsiqueira) [inline src/pipeline.jl:168]:
```suggestion
    query = fmt_join(sources...; on = on, cols = cols, fill = fill, fill_values = fill_values)
```

File: src/pipeline.jl [hunk 9]
```diff
@@ -158,12 +159,13 @@ function create_tbl(
     on::Vector{Symbol},
     cols::Vector{Symbol},
     variant::String = "",
-    fill::Union{Bool,Vector::Any} = true,
+    fill::Bool = true,
+    values::Union{Missing,Dict} = missing,
```
Comment (abelsiqueira) [inline src/pipeline.jl:163]:
```suggestion
    fill_values::Union{Missing,Dict} = missing,
```

File: src/fmtsql.jl [hunk 10]
```diff
@@ -47,22 +47,26 @@ function fmt_join(
...
-            msg = msg * "columns: $cols\n"
-            msg = msg * "defaults: $fill"
-            error(msg)
+        if ismissing(values)
+            include = join(map(c -> "IFNULL(t2.$c, t1.$c) AS $c", cols), ", ")
+        else
+            include = join(
+                map(c -> begin
+                        default = get(values, c, missing)
+                        fill_value = ismissing(default) ? "t1.$c" : fmt_quote(default)
```
[the remark this answers is not in the document]
Comment (abelsiqueira) [reply src/fmtsql.jl:62]:
```suggestion
                        value = get(fill_values, c, missing) |> fmt_quote
                        fill_value = coalesce(value, "t1.$c") ```

**Review by abelsiqueira — CHANGES_REQUESTED** [review]
Thanks for the PR, I've made some suggestions.

**Review by abelsiqueira — APPROVED** [review]
LGTM
